export const sitesRows = [
    {
      "div": 76,
      "comm": "UNI",
      "site": 475,
      "site_number": "sit",
      "job_number": "ea",
      "fischer_section": "nostrud",
      "legal_section": "exercitation",
      "purchase_date": "Wed May 15",
      "check_number": 3231,
      "is_available": false,
      "pricing_group": 8,
      "lopt_record_id": 4,
      "site_cost": "$70,141.29",
      "site_premium": "$23,393.69",
      "extra_construction": "$1,309.63"
    },
    {
      "div": 89,
      "comm": "NOR",
      "site": 865,
      "site_number": "mollit",
      "job_number": "et",
      "fischer_section": "eu",
      "legal_section": "laborum",
      "purchase_date": "Wed May 15",
      "check_number": 3941,
      "is_available": true,
      "pricing_group": 10,
      "lopt_record_id": 10,
      "site_cost": "$35,358.02",
      "site_premium": "$35,272.76",
      "extra_construction": "$9,451.28"
    },
    {
      "div": 74,
      "comm": "KIN",
      "site": 259,
      "site_number": "exercitation",
      "job_number": "tempor",
      "fischer_section": "laboris",
      "legal_section": "aliqua",
      "purchase_date": "Wed May 15",
      "check_number": 7030,
      "is_available": false,
      "pricing_group": 2,
      "lopt_record_id": 4,
      "site_cost": "$43,770.08",
      "site_premium": "$31,023.50",
      "extra_construction": "$4,572.30"
    },
    {
      "div": 53,
      "comm": "SUR",
      "site": 825,
      "site_number": "commodo",
      "job_number": "anim",
      "fischer_section": "sint",
      "legal_section": "cillum",
      "purchase_date": "Wed May 15",
      "check_number": 7187,
      "is_available": true,
      "pricing_group": 1,
      "lopt_record_id": 2,
      "site_cost": "$15,132.81",
      "site_premium": "$25,903.68",
      "extra_construction": "$7,871.27"
    },
    {
      "div": 44,
      "comm": "LEX",
      "site": 321,
      "site_number": "voluptate",
      "job_number": "Lorem",
      "fischer_section": "veniam",
      "legal_section": "eu",
      "purchase_date": "Wed May 15",
      "check_number": 7199,
      "is_available": false,
      "pricing_group": 9,
      "lopt_record_id": 6,
      "site_cost": "$33,010.38",
      "site_premium": "$33,461.21",
      "extra_construction": "$9,104.66"
    },
    {
      "div": 24,
      "comm": "MEM",
      "site": 565,
      "site_number": "aliquip",
      "job_number": "nostrud",
      "fischer_section": "ut",
      "legal_section": "pariatur",
      "purchase_date": "Wed May 15",
      "check_number": 7682,
      "is_available": false,
      "pricing_group": 0,
      "lopt_record_id": 2,
      "site_cost": "$34,094.38",
      "site_premium": "$21,727.29",
      "extra_construction": "$6,356.27"
    },
    {
      "div": 29,
      "comm": "AQU",
      "site": 693,
      "site_number": "nulla",
      "job_number": "dolore",
      "fischer_section": "id",
      "legal_section": "enim",
      "purchase_date": "Wed May 15",
      "check_number": 1049,
      "is_available": true,
      "pricing_group": 9,
      "lopt_record_id": 1,
      "site_cost": "$42,586.88",
      "site_premium": "$24,070.18",
      "extra_construction": "$5,817.67"
    },
    {
      "div": 58,
      "comm": "GEN",
      "site": 356,
      "site_number": "excepteur",
      "job_number": "deserunt",
      "fischer_section": "incididunt",
      "legal_section": "id",
      "purchase_date": "Wed May 15",
      "check_number": 1123,
      "is_available": true,
      "pricing_group": 0,
      "lopt_record_id": 7,
      "site_cost": "$98,268.48",
      "site_premium": "$21,804.66",
      "extra_construction": "$1,675.00"
    },
    {
      "div": 61,
      "comm": "WAR",
      "site": 724,
      "site_number": "velit",
      "job_number": "eiusmod",
      "fischer_section": "exercitation",
      "legal_section": "aute",
      "purchase_date": "Wed May 15",
      "check_number": 1663,
      "is_available": false,
      "pricing_group": 10,
      "lopt_record_id": 7,
      "site_cost": "$52,578.37",
      "site_premium": "$45,221.90",
      "extra_construction": "$9,738.96"
    },
    {
      "div": 57,
      "comm": "DEE",
      "site": 186,
      "site_number": "id",
      "job_number": "et",
      "fischer_section": "sunt",
      "legal_section": "non",
      "purchase_date": "Wed May 15",
      "check_number": 7430,
      "is_available": true,
      "pricing_group": 7,
      "lopt_record_id": 3,
      "site_cost": "$91,572.11",
      "site_premium": "$40,087.45",
      "extra_construction": "$7,732.79"
    },
    {
      "div": 13,
      "comm": "CAX",
      "site": 633,
      "site_number": "enim",
      "job_number": "dolor",
      "fischer_section": "commodo",
      "legal_section": "non",
      "purchase_date": "Wed May 15",
      "check_number": 8476,
      "is_available": true,
      "pricing_group": 3,
      "lopt_record_id": 5,
      "site_cost": "$37,404.65",
      "site_premium": "$42,322.29",
      "extra_construction": "$8,178.02"
    },
    {
      "div": 78,
      "comm": "DAN",
      "site": 299,
      "site_number": "laboris",
      "job_number": "consequat",
      "fischer_section": "est",
      "legal_section": "voluptate",
      "purchase_date": "Wed May 15",
      "check_number": 3648,
      "is_available": false,
      "pricing_group": 3,
      "lopt_record_id": 6,
      "site_cost": "$29,337.63",
      "site_premium": "$40,406.65",
      "extra_construction": "$2,509.73"
    },
    {
      "div": 36,
      "comm": "BIC",
      "site": 332,
      "site_number": "ut",
      "job_number": "eiusmod",
      "fischer_section": "mollit",
      "legal_section": "duis",
      "purchase_date": "Wed May 15",
      "check_number": 1453,
      "is_available": true,
      "pricing_group": 5,
      "lopt_record_id": 3,
      "site_cost": "$86,471.20",
      "site_premium": "$27,470.84",
      "extra_construction": "$4,827.36"
    },
    {
      "div": 51,
      "comm": "CAL",
      "site": 781,
      "site_number": "pariatur",
      "job_number": "mollit",
      "fischer_section": "deserunt",
      "legal_section": "culpa",
      "purchase_date": "Wed May 15",
      "check_number": 5959,
      "is_available": false,
      "pricing_group": 2,
      "lopt_record_id": 4,
      "site_cost": "$48,862.64",
      "site_premium": "$30,146.14",
      "extra_construction": "$2,904.79"
    },
    {
      "div": 89,
      "comm": "ZOL",
      "site": 203,
      "site_number": "magna",
      "job_number": "id",
      "fischer_section": "Lorem",
      "legal_section": "occaecat",
      "purchase_date": "Wed May 15",
      "check_number": 6815,
      "is_available": true,
      "pricing_group": 2,
      "lopt_record_id": 9,
      "site_cost": "$14,298.56",
      "site_premium": "$29,461.42",
      "extra_construction": "$8,589.93"
    },
    {
      "div": 18,
      "comm": "CAL",
      "site": 525,
      "site_number": "aliquip",
      "job_number": "proident",
      "fischer_section": "ut",
      "legal_section": "sunt",
      "purchase_date": "Wed May 15",
      "check_number": 6821,
      "is_available": true,
      "pricing_group": 5,
      "lopt_record_id": 10,
      "site_cost": "$23,306.64",
      "site_premium": "$23,480.37",
      "extra_construction": "$9,126.02"
    },
    {
      "div": 87,
      "comm": "UNI",
      "site": 488,
      "site_number": "sit",
      "job_number": "cupidatat",
      "fischer_section": "ut",
      "legal_section": "excepteur",
      "purchase_date": "Wed May 15",
      "check_number": 8856,
      "is_available": false,
      "pricing_group": 1,
      "lopt_record_id": 3,
      "site_cost": "$64,835.59",
      "site_premium": "$22,180.16",
      "extra_construction": "$9,443.23"
    },
    {
      "div": 41,
      "comm": "PER",
      "site": 218,
      "site_number": "pariatur",
      "job_number": "nisi",
      "fischer_section": "ipsum",
      "legal_section": "minim",
      "purchase_date": "Wed May 15",
      "check_number": 3470,
      "is_available": true,
      "pricing_group": 1,
      "lopt_record_id": 2,
      "site_cost": "$25,564.60",
      "site_premium": "$38,140.79",
      "extra_construction": "$3,865.78"
    },
    {
      "div": 23,
      "comm": "NIQ",
      "site": 130,
      "site_number": "occaecat",
      "job_number": "commodo",
      "fischer_section": "minim",
      "legal_section": "commodo",
      "purchase_date": "Wed May 15",
      "check_number": 7039,
      "is_available": false,
      "pricing_group": 2,
      "lopt_record_id": 6,
      "site_cost": "$41,441.03",
      "site_premium": "$45,799.00",
      "extra_construction": "$5,494.05"
    },
    {
      "div": 43,
      "comm": "XLE",
      "site": 492,
      "site_number": "laboris",
      "job_number": "nostrud",
      "fischer_section": "ullamco",
      "legal_section": "officia",
      "purchase_date": "Wed May 15",
      "check_number": 7469,
      "is_available": true,
      "pricing_group": 6,
      "lopt_record_id": 3,
      "site_cost": "$39,386.05",
      "site_premium": "$28,722.67",
      "extra_construction": "$6,730.97"
    },
    {
      "div": 93,
      "comm": "GRE",
      "site": 689,
      "site_number": "nulla",
      "job_number": "ullamco",
      "fischer_section": "aute",
      "legal_section": "ullamco",
      "purchase_date": "Wed May 15",
      "check_number": 7029,
      "is_available": false,
      "pricing_group": 9,
      "lopt_record_id": 3,
      "site_cost": "$78,808.57",
      "site_premium": "$32,733.24",
      "extra_construction": "$9,299.62"
    },
    {
      "div": 11,
      "comm": "TRO",
      "site": 319,
      "site_number": "laborum",
      "job_number": "sint",
      "fischer_section": "ex",
      "legal_section": "laborum",
      "purchase_date": "Wed May 15",
      "check_number": 2803,
      "is_available": true,
      "pricing_group": 5,
      "lopt_record_id": 5,
      "site_cost": "$36,613.55",
      "site_premium": "$38,165.01",
      "extra_construction": "$5,034.51"
    },
    {
      "div": 57,
      "comm": "ISO",
      "site": 639,
      "site_number": "anim",
      "job_number": "magna",
      "fischer_section": "sit",
      "legal_section": "irure",
      "purchase_date": "Wed May 15",
      "check_number": 7665,
      "is_available": true,
      "pricing_group": 3,
      "lopt_record_id": 3,
      "site_cost": "$66,786.68",
      "site_premium": "$42,841.04",
      "extra_construction": "$3,961.76"
    },
    {
      "div": 67,
      "comm": "EXO",
      "site": 772,
      "site_number": "irure",
      "job_number": "minim",
      "fischer_section": "fugiat",
      "legal_section": "laboris",
      "purchase_date": "Wed May 15",
      "check_number": 9929,
      "is_available": false,
      "pricing_group": 4,
      "lopt_record_id": 5,
      "site_cost": "$17,937.78",
      "site_premium": "$37,566.43",
      "extra_construction": "$5,612.01"
    },
    {
      "div": 55,
      "comm": "OUL",
      "site": 839,
      "site_number": "veniam",
      "job_number": "non",
      "fischer_section": "veniam",
      "legal_section": "irure",
      "purchase_date": "Wed May 15",
      "check_number": 5059,
      "is_available": true,
      "pricing_group": 10,
      "lopt_record_id": 7,
      "site_cost": "$90,700.56",
      "site_premium": "$24,893.78",
      "extra_construction": "$9,161.31"
    },
    {
      "div": 82,
      "comm": "PLA",
      "site": 323,
      "site_number": "eiusmod",
      "job_number": "ex",
      "fischer_section": "ea",
      "legal_section": "cupidatat",
      "purchase_date": "Wed May 15",
      "check_number": 6618,
      "is_available": true,
      "pricing_group": 3,
      "lopt_record_id": 5,
      "site_cost": "$71,336.60",
      "site_premium": "$23,927.54",
      "extra_construction": "$5,868.16"
    },
    {
      "div": 87,
      "comm": "OMN",
      "site": 547,
      "site_number": "laboris",
      "job_number": "sit",
      "fischer_section": "nostrud",
      "legal_section": "non",
      "purchase_date": "Wed May 15",
      "check_number": 2919,
      "is_available": true,
      "pricing_group": 1,
      "lopt_record_id": 8,
      "site_cost": "$71,059.78",
      "site_premium": "$48,708.00",
      "extra_construction": "$4,110.36"
    },
    {
      "div": 72,
      "comm": "ECL",
      "site": 718,
      "site_number": "non",
      "job_number": "id",
      "fischer_section": "excepteur",
      "legal_section": "veniam",
      "purchase_date": "Wed May 15",
      "check_number": 6747,
      "is_available": true,
      "pricing_group": 1,
      "lopt_record_id": 0,
      "site_cost": "$71,650.09",
      "site_premium": "$46,852.24",
      "extra_construction": "$4,365.54"
    },
    {
      "div": 22,
      "comm": "PRO",
      "site": 791,
      "site_number": "reprehenderit",
      "job_number": "qui",
      "fischer_section": "esse",
      "legal_section": "pariatur",
      "purchase_date": "Wed May 15",
      "check_number": 9848,
      "is_available": true,
      "pricing_group": 10,
      "lopt_record_id": 0,
      "site_cost": "$70,080.12",
      "site_premium": "$43,152.90",
      "extra_construction": "$2,411.82"
    },
    {
      "div": 51,
      "comm": "ENJ",
      "site": 675,
      "site_number": "consequat",
      "job_number": "ad",
      "fischer_section": "Lorem",
      "legal_section": "aliqua",
      "purchase_date": "Wed May 15",
      "check_number": 4874,
      "is_available": false,
      "pricing_group": 8,
      "lopt_record_id": 1,
      "site_cost": "$45,488.84",
      "site_premium": "$41,868.84",
      "extra_construction": "$2,128.96"
    },
    {
      "div": 54,
      "comm": "NEW",
      "site": 779,
      "site_number": "laborum",
      "job_number": "pariatur",
      "fischer_section": "dolor",
      "legal_section": "esse",
      "purchase_date": "Wed May 15",
      "check_number": 1602,
      "is_available": true,
      "pricing_group": 8,
      "lopt_record_id": 9,
      "site_cost": "$59,885.64",
      "site_premium": "$43,146.93",
      "extra_construction": "$8,237.88"
    },
    {
      "div": 12,
      "comm": "ISO",
      "site": 106,
      "site_number": "nostrud",
      "job_number": "consequat",
      "fischer_section": "laborum",
      "legal_section": "sint",
      "purchase_date": "Wed May 15",
      "check_number": 9390,
      "is_available": false,
      "pricing_group": 2,
      "lopt_record_id": 9,
      "site_cost": "$21,803.11",
      "site_premium": "$42,447.37",
      "extra_construction": "$4,726.64"
    },
    {
      "div": 36,
      "comm": "ZOX",
      "site": 525,
      "site_number": "reprehenderit",
      "job_number": "excepteur",
      "fischer_section": "laborum",
      "legal_section": "consectetur",
      "purchase_date": "Wed May 15",
      "check_number": 8047,
      "is_available": true,
      "pricing_group": 9,
      "lopt_record_id": 6,
      "site_cost": "$11,725.78",
      "site_premium": "$24,254.95",
      "extra_construction": "$2,974.37"
    },
    {
      "div": 28,
      "comm": "KAN",
      "site": 377,
      "site_number": "tempor",
      "job_number": "enim",
      "fischer_section": "elit",
      "legal_section": "cupidatat",
      "purchase_date": "Wed May 15",
      "check_number": 7125,
      "is_available": false,
      "pricing_group": 0,
      "lopt_record_id": 0,
      "site_cost": "$85,081.89",
      "site_premium": "$41,166.91",
      "extra_construction": "$9,442.09"
    },
    {
      "div": 61,
      "comm": "DUF",
      "site": 180,
      "site_number": "ullamco",
      "job_number": "irure",
      "fischer_section": "consequat",
      "legal_section": "adipisicing",
      "purchase_date": "Wed May 15",
      "check_number": 5925,
      "is_available": true,
      "pricing_group": 3,
      "lopt_record_id": 9,
      "site_cost": "$21,556.42",
      "site_premium": "$31,358.94",
      "extra_construction": "$4,342.45"
    },
    {
      "div": 84,
      "comm": "SON",
      "site": 549,
      "site_number": "sint",
      "job_number": "qui",
      "fischer_section": "et",
      "legal_section": "ullamco",
      "purchase_date": "Wed May 15",
      "check_number": 3874,
      "is_available": false,
      "pricing_group": 10,
      "lopt_record_id": 10,
      "site_cost": "$40,994.16",
      "site_premium": "$46,499.94",
      "extra_construction": "$6,824.84"
    },
    {
      "div": 46,
      "comm": "ELE",
      "site": 219,
      "site_number": "non",
      "job_number": "velit",
      "fischer_section": "ullamco",
      "legal_section": "in",
      "purchase_date": "Wed May 15",
      "check_number": 1412,
      "is_available": false,
      "pricing_group": 3,
      "lopt_record_id": 2,
      "site_cost": "$97,320.86",
      "site_premium": "$31,138.36",
      "extra_construction": "$5,224.71"
    },
    {
      "div": 59,
      "comm": "ZIL",
      "site": 393,
      "site_number": "cupidatat",
      "job_number": "deserunt",
      "fischer_section": "cupidatat",
      "legal_section": "occaecat",
      "purchase_date": "Wed May 15",
      "check_number": 2619,
      "is_available": false,
      "pricing_group": 10,
      "lopt_record_id": 6,
      "site_cost": "$17,543.70",
      "site_premium": "$21,985.54",
      "extra_construction": "$4,631.64"
    },
    {
      "div": 11,
      "comm": "OPT",
      "site": 884,
      "site_number": "nostrud",
      "job_number": "excepteur",
      "fischer_section": "exercitation",
      "legal_section": "et",
      "purchase_date": "Wed May 15",
      "check_number": 7875,
      "is_available": true,
      "pricing_group": 0,
      "lopt_record_id": 10,
      "site_cost": "$93,229.26",
      "site_premium": "$38,796.30",
      "extra_construction": "$8,804.55"
    },
    {
      "div": 29,
      "comm": "ZAN",
      "site": 451,
      "site_number": "et",
      "job_number": "non",
      "fischer_section": "fugiat",
      "legal_section": "ad",
      "purchase_date": "Wed May 15",
      "check_number": 5939,
      "is_available": true,
      "pricing_group": 1,
      "lopt_record_id": 6,
      "site_cost": "$19,230.37",
      "site_premium": "$22,248.66",
      "extra_construction": "$5,487.24"
    },
    {
      "div": 69,
      "comm": "SON",
      "site": 108,
      "site_number": "minim",
      "job_number": "nisi",
      "fischer_section": "sit",
      "legal_section": "officia",
      "purchase_date": "Wed May 15",
      "check_number": 3784,
      "is_available": false,
      "pricing_group": 4,
      "lopt_record_id": 0,
      "site_cost": "$12,441.78",
      "site_premium": "$32,948.92",
      "extra_construction": "$1,429.35"
    },
    {
      "div": 91,
      "comm": "MIC",
      "site": 425,
      "site_number": "cupidatat",
      "job_number": "eiusmod",
      "fischer_section": "eiusmod",
      "legal_section": "magna",
      "purchase_date": "Wed May 15",
      "check_number": 5520,
      "is_available": true,
      "pricing_group": 9,
      "lopt_record_id": 6,
      "site_cost": "$12,727.65",
      "site_premium": "$32,834.30",
      "extra_construction": "$2,320.57"
    },
    {
      "div": 52,
      "comm": "DEL",
      "site": 806,
      "site_number": "ex",
      "job_number": "aute",
      "fischer_section": "est",
      "legal_section": "Lorem",
      "purchase_date": "Wed May 15",
      "check_number": 5561,
      "is_available": true,
      "pricing_group": 6,
      "lopt_record_id": 2,
      "site_cost": "$64,021.56",
      "site_premium": "$36,486.80",
      "extra_construction": "$9,386.42"
    },
    {
      "div": 46,
      "comm": "NET",
      "site": 857,
      "site_number": "velit",
      "job_number": "est",
      "fischer_section": "cupidatat",
      "legal_section": "aliquip",
      "purchase_date": "Wed May 15",
      "check_number": 6482,
      "is_available": false,
      "pricing_group": 2,
      "lopt_record_id": 2,
      "site_cost": "$35,043.99",
      "site_premium": "$21,965.37",
      "extra_construction": "$4,156.59"
    },
    {
      "div": 46,
      "comm": "MUS",
      "site": 624,
      "site_number": "ipsum",
      "job_number": "nisi",
      "fischer_section": "enim",
      "legal_section": "eu",
      "purchase_date": "Wed May 15",
      "check_number": 1216,
      "is_available": false,
      "pricing_group": 3,
      "lopt_record_id": 3,
      "site_cost": "$71,678.81",
      "site_premium": "$27,187.91",
      "extra_construction": "$7,952.50"
    },
    {
      "div": 97,
      "comm": "STU",
      "site": 341,
      "site_number": "minim",
      "job_number": "nisi",
      "fischer_section": "fugiat",
      "legal_section": "commodo",
      "purchase_date": "Wed May 15",
      "check_number": 5971,
      "is_available": true,
      "pricing_group": 7,
      "lopt_record_id": 8,
      "site_cost": "$59,930.71",
      "site_premium": "$37,880.61",
      "extra_construction": "$5,082.32"
    },
    {
      "div": 28,
      "comm": "PRI",
      "site": 207,
      "site_number": "occaecat",
      "job_number": "ea",
      "fischer_section": "elit",
      "legal_section": "velit",
      "purchase_date": "Wed May 15",
      "check_number": 7980,
      "is_available": true,
      "pricing_group": 8,
      "lopt_record_id": 4,
      "site_cost": "$14,982.88",
      "site_premium": "$31,317.73",
      "extra_construction": "$9,374.65"
    },
    {
      "div": 24,
      "comm": "LUX",
      "site": 441,
      "site_number": "fugiat",
      "job_number": "irure",
      "fischer_section": "nostrud",
      "legal_section": "aliquip",
      "purchase_date": "Wed May 15",
      "check_number": 1569,
      "is_available": false,
      "pricing_group": 6,
      "lopt_record_id": 2,
      "site_cost": "$25,091.51",
      "site_premium": "$21,613.05",
      "extra_construction": "$1,838.64"
    }
  ];

  /*

        "div": 96,
      "comm": "ARC",
      "site": 653,
      "site_number": "aute",
      "job_number": "mollit",
      "fischer_section": "non",
      "legal_section": "quis",
      "purchase_date": "Wed May 15",
      "check_number": 9784,
      "is_available": "<ReferenceError: boolean is not defined>",
      "pricing_group": 1,
      "lopt_record_id": 9,
      "site_cost": "$47,304.55",
      "site_premium": "$36,687.71",
      "extra_construction": "$7,930.80"
      */
  export const sitesColumns = [

    { name: 'div', title: 'Div' },
    { name: 'comm', title: 'Comm' },
    { name: 'site', title: 'Site' },
    { name: 'site_number', title: 'Site Number' },
    { name: 'job_number', title: 'Job Number' },
    { name: 'fischer_section', title: 'Fischer Section' },
    { name: 'legal_section', title: 'Legal Section' },
    { name: 'purchase_date', title: 'Purchase Date' },
    { name: 'check_number', title: 'Check Number' },
    { name: 'is_available', title: 'Is Available' },
    { name: 'pricing_group', title: 'Pricing Group' },
    { name: 'lopt_record_id', title: 'lopt_record_id' },
    { name: 'site_cost', title: 'Site Cost' },
    { name: 'site_premium', title: 'Site Premium' },
    { name: 'extra_construction', title: 'Extra Construction' },
  

  ]