export const SET_OMNIBOX_FILTER = 'SET_OMNIBOX_FILTER';
export const SET_COMMUNITIES_PAGE = 'SET_COMMUNITIES_PAGE';
export const UPDATE_LAST_FETCHED_COMMUNITIES_PAGE = 'UPDATE_LAST_FETCHED_COMMUNITIES_PAGE';
export const UPDATE_COMMUNITIES_DATA = 'UPDATE_COMMUNITIES_DATA';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_FISCHER_SECTIONS_PAGE = 'SET_FISCHER_SECTIONS_PAGE';
