export const UPDATE_OMNIBOX_FILTER = 'UPDATE_OMNIBOX_FILTER';
export const UPDATE_COMMUNITIES_PAGE = 'UPDATE_COMMUNITIES_PAGE';
export const UPDATE_LAST_FETCHED_COMMUNITIES_PAGE = 'UPDATE_LAST_FETCHED_COMMUNITIES_PAGE';
export const UPDATE_COMMUNITIES_DATA = 'UPDATE_COMMUNITIES_DATA';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
